version: "3"

services:
    laravel.test:
        build:
            context: .
            dockerfile: Dockerfile
        image: myapp
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
            - /var/www/html/node_modules
        environment:
            APP_NAME: myapp
            APP_ENV: local
            APP_DEBUG: null
            APP_URL: http://localhost:8000/
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: myapp
            DB_USERNAME: root
            DB_PASSWORD: password
            CACHE_DRIVER: file
            QUEUE_CONNECTION: sync
        depends_on:
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myapp
            MYSQL_RANDOM_ROOT_PASSWORD: null
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
            - mysql:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql: